$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    dots:true,
    nav:false,
    autoplay:true,
    autoplayTimeout:2000,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:1,
            nav:true
        },
        700:{
            items:1,
            nav:true
        },
        1000:{
            items:1,
            nav:true,
            loop:true
        },
        1100:{
            items:1,
            nav:true
        }
    }
});